INSERT OR IGNORE INTO "Product" (
  "id",
  "name",
  "category",
  "price",
  "oldPrice",
  "image",
  "badge",
  "rating",
  "stock",
  "description",
  "details",
  "colors",
  "sizes",
  "sku",
  "active",
  "createdAt",
  "updatedAt"
) VALUES
(
  'camiseta-race-day',
  'Camiseta Race Day Rise',
  'Vestuario',
  89.9,
  109.9,
  '/gallery/02.jpg',
  'Mais vendida',
  4.9,
  18,
  'Camiseta leve para treinos, provas e encontros da comunidade Rise Club.',
  '["Tecido dry fit","Modelagem unissex","Secagem rapida"]',
  '["Preto","Amarelo","Branco"]',
  '["P","M","G","GG"]',
  'RC-CAM-RACE',
  true,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'regata-pace',
  'Regata Pace Livre',
  'Vestuario',
  79.9,
  NULL,
  '/gallery/03.jpg',
  'Novo',
  4.8,
  12,
  'Regata respiravel pensada para longoes e treinos de intensidade.',
  '["Recorte esportivo","Toque macio","Logo frontal"]',
  '["Preto","Cinza"]',
  '["P","M","G"]',
  'RC-REG-PACE',
  true,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'bone-rise',
  'Bone Run Club',
  'Acessorios',
  69.9,
  NULL,
  '/gallery/09.jpg',
  'Essencial',
  4.7,
  24,
  'Bone ajustavel para proteger do sol sem pesar no treino.',
  '["Aba curva","Fecho ajustavel","Tecido leve"]',
  '["Preto","Off white"]',
  '["Unico"]',
  'RC-BON-RUN',
  true,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'meia-performance',
  'Meia Performance 5K/10K',
  'Acessorios',
  39.9,
  49.9,
  '/gallery/12.jpg',
  '10% off',
  4.6,
  31,
  'Meia cano medio com conforto para rodagem e provas curtas.',
  '["Cano medio","Compressao leve","Costura confortavel"]',
  '["Preto","Amarelo"]',
  '["34-38","39-43"]',
  'RC-MEI-5K',
  true,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'garrafa-hydra',
  'Garrafa Hydra Rise 650ml',
  'Acessorios',
  54.9,
  NULL,
  '/gallery/06.jpg',
  'Treino',
  4.8,
  16,
  'Garrafa pratica para treinos na semana e encontros de fim de semana.',
  '["650ml","Tampa flip","Livre de BPA"]',
  '["Preto","Transparente"]',
  '["Unico"]',
  'RC-GAR-HYDRA',
  true,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'kit-primeiro-corre',
  'Kit Primeiro Corre',
  'Kits',
  149.9,
  179.7,
  '/gallery/01.jpg',
  'Kit',
  5,
  9,
  'Combo com camiseta, meia e garrafa para entrar na comunidade com tudo.',
  '["Economia no combo","Ideal para iniciantes","Pronto para presente"]',
  '["Preto"]',
  '["P","M","G","GG"]',
  'RC-KIT-01',
  true,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);

INSERT OR IGNORE INTO "Coupon" (
  "code",
  "type",
  "value",
  "minSubtotal",
  "active",
  "createdAt",
  "updatedAt"
) VALUES
(
  'RISE10',
  'percent',
  10,
  0,
  true,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
),
(
  'FRETEOFF',
  'fixed',
  18.9,
  120,
  true,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
);
